# permissions for end users to edit vernemqs.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: vernemq-editor-role
rules:
- apiGroups:
  - vmq.k8s.vernemq.com
  resources:
  - vernemqs
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - vmq.k8s.vernemq.com
  resources:
  - vernemqs/status
  verbs:
  - get
